# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Category.create([
  { :name => nil, :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Client.create([
  { :name => "KFC", :description => "  KFC food", :address_line1 => "Punjagutaa Rd", :address_line2 => "Somajiguda", :city => "hyderabad", :state => "AP", :country => "India", :postal_code => 500072, :email => "kfc@yahoo.com", :phone_no => "040-66051356", :image_url => "http://www.kfc.co.in/images/kfc-sogood.png", :created_at => "2013-03-13 09:38:11", :updated_at => "2013-03-13 09:38:11" }
], :without_protection => true )



Product.create([
  { :sku => "BG001", :name => "Burger", :description => "  KFC burger", :image_url => "http://www.kfc.co.in/images/pro/Chicken_Zinger.png", :status => true, :created_at => "2013-03-13 09:41:05", :updated_at => "2013-03-13 09:41:05", :client_id => 2 },
  { :sku => "MEAL003", :name => "KFC meal", :description => "  KFC meal", :image_url => "http://www.kfc.co.in/images/pro/ZingKongbox_Chicken.png", :status => true, :created_at => "2013-03-13 09:48:03", :updated_at => "2013-03-13 09:48:03", :client_id => 2 },
  { :sku => "WING001", :name => "KFC wings", :description => "KFC wings", :image_url => "http://www.kfc.co.in/images/pro/snacks_6-Pc-Hot-Wings.png", :status => true, :created_at => "2013-03-13 09:53:52", :updated_at => "2013-03-13 09:53:52", :client_id => 2 },
  { :sku => "POP001", :name => "KFC Pop corn large", :description => "  KFC pop corn", :image_url => "http://www.kfc.co.in/images/pro/Snacks_popcornchicken.png", :status => true, :created_at => "2013-03-13 10:14:49", :updated_at => "2013-03-13 10:14:49", :client_id => 2 },
  { :sku => "TW123", :name => "KFC twister", :description => "  KFC twister", :image_url => "http://www.kfc.co.in/images/pro/toasted_Twister.png", :status => true, :created_at => "2013-03-13 10:39:52", :updated_at => "2013-03-13 10:39:52", :client_id => 2 },
  { :sku => "ZNG001", :name => "KFC zingkong box", :description => "  KFC zing box", :image_url => "http://www.kfc.co.in/images/pro/ZingKongbox_Chicken.png", :status => true, :created_at => "2013-03-13 10:54:31", :updated_at => "2013-03-13 10:54:31", :client_id => 2 },
  { :sku => "ST123", :name => "test", :description => "  test", :image_url => "test", :status => false, :created_at => "2013-03-13 12:47:45", :updated_at => "2013-03-13 12:47:45", :client_id => 2 }
], :without_protection => true )



ProductPrice.create([
  { :product_id => 4, :client_id => 2, :price => 99.0, :discount => 10, :valid_from => nil, :valid_to => nil, :created_at => "2013-03-13 09:41:05", :updated_at => "2013-03-13 09:41:05" },
  { :product_id => 5, :client_id => 2, :price => 123.0, :discount => 0, :valid_from => nil, :valid_to => nil, :created_at => "2013-03-13 09:48:03", :updated_at => "2013-03-13 09:48:03" },
  { :product_id => 6, :client_id => 2, :price => 199.0, :discount => 0, :valid_from => nil, :valid_to => nil, :created_at => "2013-03-13 09:53:52", :updated_at => "2013-03-13 09:53:52" },
  { :product_id => 7, :client_id => 2, :price => 150.0, :discount => 0, :valid_from => nil, :valid_to => nil, :created_at => "2013-03-13 10:14:49", :updated_at => "2013-03-13 10:14:49" },
  { :product_id => 8, :client_id => 2, :price => 99.0, :discount => 0, :valid_from => nil, :valid_to => nil, :created_at => "2013-03-13 10:39:52", :updated_at => "2013-03-13 10:39:52" },
  { :product_id => 9, :client_id => nil, :price => 156.0, :discount => 0, :valid_from => "2013-03-13", :valid_to => "2013-03-15", :created_at => "2013-03-13 10:54:31", :updated_at => "2013-03-13 10:54:31" },
  { :product_id => 10, :client_id => nil, :price => 123.0, :discount => 0, :valid_from => "2013-03-13", :valid_to => "2013-03-14", :created_at => "2013-03-13 12:47:45", :updated_at => "2013-03-13 12:47:45" }
], :without_protection => true )



Role.create([
  { :name => nil, :resource_id => nil, :resource_type => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



User.create([
  { :email => "sumanth.nitw@gmail.com", :encrypted_password => "$2a$10$tJCdcpXFBj7BVMRahfqGW.hGhMp53w0ycFwfKJz1CCk1g7n5xW8vm", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 4, :current_sign_in_at => "2013-03-13 03:34:45", :last_sign_in_at => "2013-03-12 17:29:40", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-03-08 11:08:37", :updated_at => "2013-03-13 03:34:45", :name => "sumanth.nitw" }
], :without_protection => true )


